# Generated by Django 4.2.8 on 2024-01-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemincart',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
